name: Build PDF on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: cv_joris_de_josselin_de_jong.tex

    - name: Rename PDF with version
      run: mv cv_joris_de_josselin_de_jong.pdf cv_joris_de_josselin_de_jong_${{ github.event.release.tag_name }}.pdf

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CV-PDF
        path: cv_joris_de_josselin_de_jong_${{ github.event.release.tag_name }}.pdf

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: cv_joris_de_josselin_de_jong_${{ github.event.release.tag_name }}.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
